trained_adapters_path:
  - "trained_pefts/medical_pubmed_lora/medical_pubmed_lora"
  - "trained_pefts/medical_pubmed_ia3/medical_pubmed_ia3"

test_domain: "medical"
test_dataset_name: "pubmed"
mlm: True
training_samples: 1
eval_samples: 1
test_samples: 50
sorted_dataset: True
chat_template: True
provider: "hf"
instruct_mode: True
metric: "rouge"
torch_dtype: "bf16"